name: Run Python Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libegl1 \
          libxkbcommon-x11-0 \
          libxcb-cursor0 \
          libx11-xcb1 \
          libxcb1 \
          libxcb-render0 \
          libxcb-shape0 \
          libxcb-shm0 \
          libxcb-xfixes0 \
          libxcb-icccm4 \
          libxcb-image0 \
          libxcb-keysyms1 \
          libxcb-randr0 \
          libxcb-render-util0 \
          libxcb-util1 \
          libxcb-xinerama0 \
          libxcb-xkb1 \
          libxrender1 \
          libxi6 \
          libxcomposite1 \
          libxcursor1 \
          libxdamage1 \
          libxtst6 \
          libnss3 \
          libdbus-1-3 \
          libatk-bridge2.0-0 \
          libatspi2.0-0 \
          x11-utils \
          xvfb

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PySide6
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run tests
      run: |
        xvfb-run -s "-screen 0 1920x1080x24" python tests/run_tests.py

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test_results.md
        if-no-files-found: error
