name: Run Python Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PySide6
        if exist requirements.txt pip install -r requirements.txt

    - name: Run tests
      run: python tests/run_tests.py

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test_results.md
        if-no-files-found: error
