name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y ppa:oibaf/graphics-drivers
          sudo apt-get update
          sudo apt-get install -y libegl1-mesa libxcb-xinerama0
          pip install -r requirements.txt

      - name: Run tests
        run: python tests/run_tests.py
